### ISSUE TITLE
IndexError: index 53023 is out of bounds for axis 0 with size 53023 , when training feature extractor

### ISSUE THREAD

**Issue by nirvikara** [jbohnslav/deepethogram#102]
When I try training the feature extractor, it reaches epoch 4 and then the training ends with the following error - 

```
`Epoch 4: 100%|█████████████████████████████████████████████████| 2000/2000 [17:59<00:00,  1.85it/s, loss=0.25, v_num=0]
Epoch 5:   0%|                                                            | 0/2000 [00:00<?, ?it/s, loss=0.25, v_num=0]C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\kornia\augmentation\augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
Epoch 5:   2%|█▎                                                | 50/2000 [00:49<32:26,  1.00it/s, loss=0.311, v_num=0]Saving latest checkpoint...
Epoch 5:   2%|█▎                                                | 50/2000 [00:54<35:30,  1.09s/it, loss=0.311, v_num=0]
Traceback (most recent call last):
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 645, in <module>
    feature_extractor_train(cfg)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 182, in feature_extractor_train
    trainer.fit(lightning_module)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 57, in train
    return self.train_or_test()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 542, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\profiler\profilers.py", line 85, in profile_iterable
    value = next(iterator)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 47, in _with_is_last
    for val in it:
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 406, in __getitem__
    return self.dataset[index]
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\torch\utils\data\dataset.py", line 218, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "C:\Users\Herzog\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 364, in __getitem__
    label = self.labels[index]
IndexError: index 53023 is out of bounds for axis 0 with size 53023

[2022-03-30 05:03:25,694] INFO [deepethogram.gui.main.featureextractor_train:390] Training finished. If you see error messages above, training did not complete successfully.
[2022-03-30 05:03:25,694] INFO [deepethogram.gui.main.featureextractor_train:395] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-03-30 05:03:25,860] INFO [deepethogram.gui.main.project_loaded_buttons:173] Number finalized labels: 19`
```

I have tried setting up new project several times and still get the same error.

**Comment by nirvikara** [comment]
fixed this by reducing batch_size to 8. Closing Issue.
