### ISSUE TITLE
AssertionError when Training Sequence Model

### ISSUE THREAD

**Issue by brunswickchad** [jbohnslav/deepethogram#103]
Hi,

I trained the FlowGenerator and FeatureExtractor fine and have .h5 files in every DATA directory, but the Sequence Model returns an Assertion Error and doesn't train. See below. 

I've tried reinstalling DEG and making a new project directory.

```
[2022-04-14 18:26:10,333] INFO [deepethogram.gui.main.initialize_project:1007] cwd: C:\DEG_Master_2_deepethogram\gui_logs\220414_182610
[2022-04-14 18:26:11,437] INFO [deepethogram.gui.main.project_loaded_buttons:173] Number finalized labels: 120
[2022-04-14 18:26:12,574] INFO [deepethogram.gui.main.initialize_video:221] Record for loaded video: {'flow': None, 'label': 'C:\\DEG_Master_2_deepethogram\\DATA\\trimmed_young_rsc_kd_Trial32.4\\trimmed_young_rsc_kd_Trial32.4_labels.csv', 'output': 'C:\\DEG_Master_2_deepethogram\\DATA\\trimmed_young_rsc_kd_Trial32.4\\trimmed_young_rsc_kd_Trial32.4_outputs.h5', 'rgb': 'C:\\DEG_Master_2_deepethogram\\DATA\\trimmed_young_rsc_kd_Trial32.4\\trimmed_young_rsc_kd_Trial32.4.mp4', 'keypoint': None, 'key': 'trimmed_young_rsc_kd_Trial32.4'}
[2022-04-14 18:26:12,610] INFO [deepethogram.projects.import_outputfile:776] Key used to load outputfile: resnet18
[2022-04-14 18:26:13,467] INFO [deepethogram.gui.main.import_outputfile:871] CHANGING LATENT NAME TO : resnet18
[2022-04-14 18:26:17,723] INFO [deepethogram.gui.main.get_selected_models:1118] {'flow_generator': {'no pretrained weights': None, '200221_115158_TinyMotionNet': 'C:\\DEG_Master_2_deepethogram\\models\\pretrained_models\\200221_115158_TinyMotionNet\\checkpoint.pt', '220412_183229_flow_generator_train': 'C:\\DEG_Master_2_deepethogram\\models\\220412_183229_flow_generator_train\\checkpoint.pt', '220412_211356_flow_generator_train': 'C:\\DEG_Master_2_deepethogram\\models\\220412_211356_flow_generator_train\\lightning_checkpoints\\epoch=1-step=1999.ckpt', '220413_034155_flow_generator_train': 'C:\\DEG_Master_2_deepethogram\\models\\220413_034155_flow_generator_train\\lightning_checkpoints\\epoch=0-step=999.ckpt', '220413_065240_flow_generator_train': 'C:\\DEG_Master_2_deepethogram\\models\\220413_065240_flow_generator_train\\lightning_checkpoints\\epoch=0-step=999.ckpt'}, 'feature_extractor': {'no pretrained weights': None, '200415_125824_hidden_two_stream_kinetics_degf': 'C:\\DEG_Master_2_deepethogram\\models\\pretrained_models\\200415_125824_hidden_two_stream_kinetics_degf\\checkpoint.pt', '220413_071204_feature_extractor_train': 'C:\\DEG_Master_2_deepethogram\\models\\220413_071204_feature_extractor_train\\lightning_checkpoints\\epoch=17-step=17999.ckpt'}, 'sequence': {'': None}}
[2022-04-14 18:26:20,084] INFO [deepethogram.projects.convert_config_paths_to_absolute:1120] cwd in absolute: C:\DEG_Master_2_deepethogram\gui_logs\220414_182610
[2022-04-14 18:26:20,085] INFO [deepethogram.projects.convert_config_paths_to_absolute:1164] after absolute: {'class_names': ['background', 'Left', 'Right', 'Bottom'], 'config_file': 'C:\\DEG_Master_2_deepethogram\\project_config.yaml', 'data_path': 'C:\\DEG_Master_2_deepethogram\\DATA', 'labeler': None, 'model_path': 'C:\\DEG_Master_2_deepethogram\\models', 'name': 'DEG_Master_2', 'path': 'C:\\DEG_Master_2_deepethogram', 'pretrained_path': 'C:\\DEG_Master_2_deepethogram\\models\\pretrained_models'}
[2022-04-14 18:26:20,096] INFO [__main__.sequence_train:43] args: C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\sequence\train.py project.path=C:\DEG_Master_2_deepethogram
[2022-04-14 18:26:20,096] INFO [__main__.sequence_train:49] Configuration used:
[2022-04-14 18:26:20,105] INFO [__main__.sequence_train:50] split:
  reload: true
  file: null
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
compute:
  fp16: false
  num_workers: 8
  batch_size: 32
  min_batch_size: 8
  max_batch_size: 512
  distributed: false
  gpu_id: 0
  dali: false
  metrics_workers: 0
reload:
  overwrite_cfg: false
  latest: false
notes: null
log:
  level: info
feature_extractor:
  arch: resnet18
  fusion: average
  sampler: null
  final_bn: false
  sampling_ratio: null
  final_activation: sigmoid
  dropout_p: 0.25
  n_flows: 10
  n_rgb: 1
  curriculum: false
  inputs: both
  weights: pretrained
train:
  steps_per_epoch:
    train: 1000
    val: 1000
    test: 20
  num_epochs: 100
  lr: 0.0001
  scheduler: plateau
  min_lr: 5.0e-07
  stopping_type: learning_rate
  milestones:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  weight_loss: true
  patience: 5
  early_stopping_begins: 0
  viz_metrics: true
  viz_examples: 10
  reduction_factor: 0.1
  loss_weight_exp: 1.0
  loss_gamma: 1.0
  label_smoothing: 0.05
  oversampling_exp: 0.0
  regularization:
    style: l2
    alpha: 0.01
    beta: 0.001
sequence:
  arch: tgmj
  latent_name: resnet18
  output_name: null
  sequence_length: 180
  dropout_p: 0.5
  num_layers: 3
  hidden_size: 64
  nonoverlapping: true
  filter_length: 15
  input_dropout: 0.5
  n_filters: 8
  tgm_reduction: max
  c_in: 1
  c_out: 8
  soft_attn: true
  num_features: 128
  bidirectional: false
  rnn_style: lstm
  hidden_dropout: 0.0
  weights: null
  nonlinear_classification: true
  final_bn: true
  input_type: features
augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    'N': 141592500
    mean:
    - 0.40638869448261355
    - 0.41416819662335386
    - 0.4025001932707336
    std:
    - 0.0825892040410579
    - 0.08290470159718286
    - 0.08242711179662619
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
cmap: deepethogram
control_arrow_jump: 31
label_view_width: 31
postprocessor:
  min_bout_length: 1
  type: min_bout_per_behavior
prediction_opacity: 0.2
project:
  class_names:
  - background
  - Left
  - Right
  - Bottom
  config_file: C:\DEG_Master_2_deepethogram\project_config.yaml
  data_path: C:\DEG_Master_2_deepethogram\DATA
  labeler: null
  model_path: C:\DEG_Master_2_deepethogram\models
  name: DEG_Master_2
  path: C:\DEG_Master_2_deepethogram
  pretrained_path: C:\DEG_Master_2_deepethogram\models\pretrained_models
run:
  type: train
  model: sequence
  dir: C:\DEG_Master_2_deepethogram\models\220414_182620_sequence_train
unlabeled_alpha: 0.1
vertical_arrow_jump: 3

Traceback (most recent call last):
  File "C:\Users\Chad\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Chad\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\sequence\train.py", line 265, in <module>
    sequence_train(cfg)
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\sequence\train.py", line 52, in sequence_train
    datasets, data_info = get_datasets_from_cfg(cfg, 'sequence')
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 1205, in get_datasets_from_cfg
    is_keypoint=cfg.sequence.input_type == 'keypoints')
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 1112, in get_sequence_datasets
    stack_in_time=stack_in_time)
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 784, in __init__
    dataset = FeatureVectorDataset(datafile, labelfile, *args, **kwargs)
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 710, in __init__
    self.verify_dataset()
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\data\datasets.py", line 726, in verify_dataset
    assert self.logit_key in f
AssertionError
[2022-04-14 18:26:21,756] INFO [deepethogram.gui.main.sequence_train:496] Training finished. If you see error messages above, training did not complete successfully.
[2022-04-14 18:26:21,757] INFO [deepethogram.gui.main.sequence_train:501] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-04-14 18:26:22,589] INFO [deepethogram.gui.main.project_loaded_buttons:173] Number finalized labels: 120
Traceback (most recent call last):
  File "C:\Users\Chad\anaconda3\envs\deg\lib\site-packages\deepethogram\gui\main.py", line 944, in open_avi_browser
    raise ValueError('Could not open file: {}'.format(filename))
ValueError: Could not open file:
```

**Comment by rcalfredson** [comment]
I encountered this problem recently, and ended up resolving it by generating fresh inferences on my data using the feature extractor. Hope this may be useful for you!

**Comment by jbohnslav** [comment]
Assuming @rcalfredson's fix worked, closing.
