### ISSUE TITLE
Feature Extractor Errors

### ISSUE THREAD

**Issue by kcrisco22** [jbohnslav/deepethogram#109]
Hi-- when I am running my feature extractor (which last week on 7/29 worked) it is now crashing with the following error.  

[2022-08-01 16:49:34,506] INFO [deepethogram.base.get_train_sampler:171] not using oversampling
/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:96: LightningDeprecationWarning: Setting `Trainer(progress_bar_refresh_rate=1)` is deprecated in v1.5 and will be removed in v1.7. Please pass `pytorch_lightning.callbacks.progress.TQDMProgressBar` with `refresh_rate` directly to the Trainer's `callbacks` argument instead. Or, to disable the progress bar pass `enable_progress_bar = False` to the Trainer.
  rank_zero_deprecation(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:342: LightningDeprecationWarning: Base `Callback.on_train_batch_start` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
  rank_zero_deprecation(
/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:342: LightningDeprecationWarning: Base `Callback.on_train_batch_end` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
  rank_zero_deprecation(
/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:335: LightningDeprecationWarning: The `on_keyboard_interrupt` callback hook was deprecated in v1.5 and will be removed in v1.7. Please use the `on_exception` callback hook instead.
  rank_zero_deprecation(
Missing logger folder: /media/ssd-1/VAME/ForcedSwim-Jan19-2022/KO_DIG/KO_SPS_DIG_deepethogram/models/220801_164931_feature_extractor_train/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[2022-08-01 16:49:38,280] INFO [deepethogram.base.configure_optimizers:227] learning rate: 0.0001

  | Name       | Type               | Params
--------------------------------------------------
0 | model      | HiddenTwoStream    | 24.4 M
1 | activation | Sigmoid            | 0     
2 | criterion  | ClassificationLoss | 0     
--------------------------------------------------
22.4 M    Trainable params
2.0 M     Non-trainable params
24.4 M    Total params
97.457    Total estimated model params size (MB)
/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:495: PossibleUserWarning: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test/predict dataloaders.
  rank_zero_warn(
Epoch 0:   0%|                                         | 1/2000 [00:05<3:10:23,  5.71s/itEpoch 0:   0%|                                         | 1/2000 [00:05<3:10:24,  5.71s/itEpoch 0:   0%|                    | 1/2000 [00:05<3:10:31,  5.72s/it, lossEpoch 0:   0%|              | 2/2000 [00:08<2:24:34,  4.34s/it, loss=0.887, v_num=0]Epoch 0:   3%|▍              | 66/2000 [00:44<21:57,  1.47it/s, loss=0.475, v_num=0][2022-08-01 16:50:23,329] INFO [deepethogram.gui.main.log_idle:151] User has been idle for 60.0 seconds...
Epoch 0:  65%|████████▍    | 1305/2000 [13:45<07:19,  1.58it/s, loss=0.346, v_num=0]Traceback (most recent call last):█▊             | 305/1000 [03:19<10:41,  1.08it/s]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/deepethogram/feature_extractor/train.py", line 646, in <module>
    feature_extractor_train(cfg)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/deepethogram/feature_extractor/train.py", line 182, in feature_extractor_train
    trainer.fit(lightning_module)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
    self._run_validation()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 309, in _run_validation
    self.val_loop.run()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 112, in advance
    batch = next(data_fetcher)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/deepethogram/data/datasets.py", line 342, in __getitem__
    image = reader[i + start_frame]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/vidio/read.py", line 70, in __getitem__
    return self.read(*args, **kwargs)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/vidio/read.py", line 115, in read
    raise ValueError('error decoding frame {} from video {}'.format(framenum, self.filename))
ValueError: error decoding frame 17995 from video /media/ssd-1/VAME/ForcedSwim-Jan19-2022/KO_DIG/KO_SPS_DIG_deepethogram/DATA/M5 Dirty/M5 Dirty.mp4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/deepethogram/data/datasets.py", line 415, in __getitem__
    return self.dataset[index]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/pjmxeon/anaconda3/envs/deg/lib/python3.8/site-packages/deepethogram/data/datasets.py", line 344, in __getitem__
    image = self._zeros_image.copy().transpose(1, 2, 0)
AttributeError: 'NoneType' object has no attribute 'copy'

[2022-08-01 17:03:26,071] INFO [deepethogram.gui.main.featureextractor_train:395] Training finished. If you see error messages above, training did not complete successfully.
[2022-08-01 17:03:26,071] INFO [deepethogram.gui.main.featureextractor_train:400] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-08-01 17:03:26,122] INFO [deepethogram.gui.main.project_loaded_buttons:175] Number finalized labels: 5

**Comment by Cumol** [comment]
@kcrisco22 any update on how this was solved?
