### ISSUE TITLE
FeatureExtractor inference errors: 'metrics_by_threshold' and 'threshold_curves' do not exist

### ISSUE THREAD

**Issue by birtezuidinga** [jbohnslav/deepethogram#113]
I have been trying to do inference on new videos based on my currently trained model, but I cannot get it to work anymore on the computer I was using, and also on another computer with a fresh deepethogram installation. I get errors that 'metrics_by_threshold' and 'threshold_curves' do not exist. See error messages below. 

Does anyone know how to fix this? It might be related to https://github.com/jbohnslav/deepethogram/issues/111, since training the flow generator also gave me "TypeError: init() got an unexpected keyword argument 'progress_bar_refresh_rate'".

```
(deg) C:\Users\zuidinga\Documents>python -m deepethogram
[2022-09-05 14:29:51,056] INFO [deepethogram.gui.main.setup_gui_cfg:1268] CWD: C:\Users\zuidinga\Documents
[2022-09-05 14:29:51,056] INFO [deepethogram.gui.main.setup_gui_cfg:1269] Configuration used: split:
  reload: true
  file: null
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
compute:
  fp16: false
  num_workers: 8
  batch_size: auto
  min_batch_size: 8
  max_batch_size: 512
  distributed: false
  gpu_id: 0
  dali: false
  metrics_workers: 0
reload:
  overwrite_cfg: false
  latest: false
notes: null
log:
  level: info
run:
  type: gui
label_view_width: 31
control_arrow_jump: 31
vertical_arrow_jump: 3
cmap: deepethogram
unlabeled_alpha: 0.1
prediction_opacity: 0.2

[2022-09-05 14:30:04,829] INFO [deepethogram.gui.main.initialize_project:1017] cwd: C:\Users\zuidinga\Documents
[2022-09-05 14:30:04,829] INFO [deepethogram.projects.convert_config_paths_to_absolute:1135] cwd in absolute: C:\Users\zuidinga\Documents
[2022-09-05 14:30:04,829] INFO [deepethogram.projects.convert_config_paths_to_absolute:1178] after absolute: {'class_names': ['background', 'fly', 'groom', 'landing_response'], 'config_file': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\project_config.yaml', 'data_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\DATA', 'labeler': None, 'model_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models', 'name': 'Tethered_Flight_pin', 'path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram', 'pretrained_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models'}
[2022-09-05 14:30:04,829] INFO [deepethogram.gui.main.initialize_project:1019] cwd: C:\Users\zuidinga\Documents
[2022-09-05 14:30:04,844] INFO [deepethogram.gui.main.initialize_project:1021] loaded project configuration: split:
  reload: true
  file: null
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
compute:
  fp16: false
  num_workers: 8
  batch_size: 32
  min_batch_size: 8
  max_batch_size: 512
  distributed: false
  gpu_id: 0
  dali: false
  metrics_workers: 0
reload:
  overwrite_cfg: false
  latest: false
notes: null
log:
  level: info
run:
  type: gui
  model: null
  dir: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\gui_logs\220905_143004
label_view_width: 31
control_arrow_jump: 31
vertical_arrow_jump: 3
cmap: deepethogram
unlabeled_alpha: 0.1
prediction_opacity: 0.2
postprocessor:
  type: min_bout_per_behavior
  min_bout_length: 1
augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    'N': 10880000
    mean:
    - 0.06458641255767011
    - 0.06458641255767011
    - 0.06458641255767011
    std:
    - 0.1453893246030677
    - 0.1453893246030677
    - 0.1453893246030677
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
project:
  class_names:
  - background
  - fly
  - groom
  - landing_response
  config_file: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\project_config.yaml
  data_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA
  labeler: null
  model_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models
  name: Tethered_Flight_pin
  path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram
  pretrained_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\pretrained_models
sequence:
  filter_length: 15
train:
  loss_weight_exp: 1.0

[2022-09-05 14:30:04,844] INFO [deepethogram.gui.main.initialize_project:1022] cwd: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\gui_logs\220905_143004
[2022-09-05 14:30:04,860] INFO [deepethogram.gui.main.project_loaded_buttons:175] Number finalized labels: 0
[2022-09-05 14:30:08,328] INFO [deepethogram.gui.main.initialize_video:226] Record for loaded video: {'flow': None, 'label': None, 'output': None, 'rgb': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\DATA\\220902_f94_144036_video\\220902_f94_144036_video.mp4', 'keypoint': None, 'key': '220902_f94_144036_video'}
[2022-09-05 14:30:14,937] INFO [deepethogram.gui.main.get_selected_models:1136] {'flow_generator': {'no pretrained weights': None, '200221_115158_TinyMotionNet': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models\\200221_115158_TinyMotionNet\\checkpoint.pt', '220209_142218_flow_generator_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220209_142218_flow_generator_train\\lightning_checkpoints\\epoch=0-step=999.ckpt'}, 'feature_extractor': {'no pretrained weights': None, '200415_125824_hidden_two_stream_kinetics_degf': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models\\200415_125824_hidden_two_stream_kinetics_degf\\checkpoint.pt', '220210_091650_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220210_091650_feature_extractor_train\\lightning_checkpoints\\epoch=6-step=6999.ckpt', '220211_173849_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220211_173849_feature_extractor_train\\lightning_checkpoints\\epoch=15-step=15999.ckpt', '220214_184400_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_184400_feature_extractor_train\\lightning_checkpoints\\epoch=13-step=13999.ckpt', '220216_151052_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220216_151052_feature_extractor_train\\lightning_checkpoints\\epoch=18-step=18999.ckpt', '220217_181004_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220217_181004_feature_extractor_train\\lightning_checkpoints\\epoch=15-step=15999.ckpt', '220308_175511_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220308_175511_feature_extractor_train\\lightning_checkpoints\\epoch=3-step=3999.ckpt', '220330_154754_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220330_154754_feature_extractor_train\\lightning_checkpoints\\epoch=14-step=14999.ckpt', '220726_000617_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220726_000617_feature_extractor_train\\checkpoint.pt'}, 'sequence': {'': None, 'no pretrained weights': None, '220210_182658_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220210_182658_sequence_train\\lightning_checkpoints\\epoch=21-step=263.ckpt', '220214_085641_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_085641_sequence_train\\lightning_checkpoints\\epoch=39-step=2719.ckpt', '220214_220016_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_220016_sequence_train\\lightning_checkpoints\\epoch=27-step=4059.ckpt', '220216_212000_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220216_212000_sequence_train\\lightning_checkpoints\\epoch=41-step=7979.ckpt', '220217_214344_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220217_214344_sequence_train\\lightning_checkpoints\\epoch=26-step=5777.ckpt', '220308_220315_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220308_220315_sequence_train\\lightning_checkpoints\\epoch=33-step=8329.ckpt', '220330_185014_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220330_185014_sequence_train\\lightning_checkpoints\\epoch=28-step=9105.ckpt', '220726_102833_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220726_102833_sequence_train\\lightning_checkpoints\\epoch=18-step=15142.ckpt'}}
[2022-09-05 14:30:14,937] INFO [deepethogram.gui.main.get_selected_models:1136] {'flow_generator': {'no pretrained weights': None, '200221_115158_TinyMotionNet': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models\\200221_115158_TinyMotionNet\\checkpoint.pt', '220209_142218_flow_generator_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220209_142218_flow_generator_train\\lightning_checkpoints\\epoch=0-step=999.ckpt'}, 'feature_extractor': {'no pretrained weights': None, '200415_125824_hidden_two_stream_kinetics_degf': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models\\200415_125824_hidden_two_stream_kinetics_degf\\checkpoint.pt', '220210_091650_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220210_091650_feature_extractor_train\\lightning_checkpoints\\epoch=6-step=6999.ckpt', '220211_173849_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220211_173849_feature_extractor_train\\lightning_checkpoints\\epoch=15-step=15999.ckpt', '220214_184400_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_184400_feature_extractor_train\\lightning_checkpoints\\epoch=13-step=13999.ckpt', '220216_151052_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220216_151052_feature_extractor_train\\lightning_checkpoints\\epoch=18-step=18999.ckpt', '220217_181004_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220217_181004_feature_extractor_train\\lightning_checkpoints\\epoch=15-step=15999.ckpt', '220308_175511_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220308_175511_feature_extractor_train\\lightning_checkpoints\\epoch=3-step=3999.ckpt', '220330_154754_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220330_154754_feature_extractor_train\\lightning_checkpoints\\epoch=14-step=14999.ckpt', '220726_000617_feature_extractor_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220726_000617_feature_extractor_train\\checkpoint.pt'}, 'sequence': {'': None, 'no pretrained weights': None, '220210_182658_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220210_182658_sequence_train\\lightning_checkpoints\\epoch=21-step=263.ckpt', '220214_085641_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_085641_sequence_train\\lightning_checkpoints\\epoch=39-step=2719.ckpt', '220214_220016_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220214_220016_sequence_train\\lightning_checkpoints\\epoch=27-step=4059.ckpt', '220216_212000_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220216_212000_sequence_train\\lightning_checkpoints\\epoch=41-step=7979.ckpt', '220217_214344_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220217_214344_sequence_train\\lightning_checkpoints\\epoch=26-step=5777.ckpt', '220308_220315_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220308_220315_sequence_train\\lightning_checkpoints\\epoch=33-step=8329.ckpt', '220330_185014_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220330_185014_sequence_train\\lightning_checkpoints\\epoch=28-step=9105.ckpt', '220726_102833_sequence_train': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\220726_102833_sequence_train\\lightning_checkpoints\\epoch=18-step=15142.ckpt'}}
[2022-09-05 14:30:14,937] INFO [deepethogram.gui.main.featureextractor_infer:452] inference running with args: python -m deepethogram.feature_extractor.inference project.path=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram inference.overwrite=True feature_extractor.weights=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt flow_generator.weights=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220209_142218_flow_generator_train\lightning_checkpoints\epoch=0-step=999.ckpt inference.directory_list=[D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144036_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144307_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144421_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144544_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144738_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144904_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145032_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145209_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145327_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145454_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145714_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145939_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150104_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150321_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150726_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150924_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151138_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151246_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151927_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152207_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152335_video]
[2022-09-05 14:30:17,443] INFO [deepethogram.projects.convert_config_paths_to_absolute:1135] cwd in absolute: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\gui_logs\220905_143004
[2022-09-05 14:30:17,443] INFO [deepethogram.projects.convert_config_paths_to_absolute:1178] after absolute: {'class_names': ['background', 'fly', 'groom', 'landing_response'], 'config_file': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\project_config.yaml', 'data_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\DATA', 'labeler': None, 'model_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models', 'name': 'Tethered_Flight_pin', 'path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram', 'pretrained_path': 'D:\\DeepEthogram_pin\\Tethered_Flight_pin_deepethogram\\models\\pretrained_models'}
[2022-09-05 14:30:17,459] INFO [__main__.feature_extractor_inference:473] args: C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\inference.py project.path=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram inference.overwrite=True feature_extractor.weights=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt flow_generator.weights=D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220209_142218_flow_generator_train\lightning_checkpoints\epoch=0-step=999.ckpt inference.directory_list=[D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144036_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144307_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144421_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144544_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144738_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144904_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145032_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145209_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145327_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145454_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145714_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145939_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150104_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150321_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150726_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150924_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151138_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151246_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151927_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152207_video,D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152335_video]
[2022-09-05 14:30:17,459] INFO [__main__.feature_extractor_inference:475] configuration used in inference:
[2022-09-05 14:30:17,459] INFO [__main__.feature_extractor_inference:476] split:
  reload: true
  file: null
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
compute:
  fp16: false
  num_workers: 8
  batch_size: 32
  min_batch_size: 8
  max_batch_size: 512
  distributed: false
  gpu_id: 0
  dali: false
  metrics_workers: 0
reload:
  overwrite_cfg: false
  latest: false
notes: null
log:
  level: info
augs:
  brightness: 0.25
  contrast: 0.1
  hue: 0.1
  saturation: 0.1
  color_p: 0.5
  grayscale: 0.5
  crop_size: null
  resize:
  - 224
  - 224
  dali: false
  random_resize: false
  pad: null
  LR: 0.5
  UD: 0.0
  degrees: 10
  normalization:
    'N': 10880000
    mean:
    - 0.06458641255767011
    - 0.06458641255767011
    - 0.06458641255767011
    std:
    - 0.1453893246030677
    - 0.1453893246030677
    - 0.1453893246030677
feature_extractor:
  arch: resnet18
  fusion: average
  sampler: null
  final_bn: false
  sampling_ratio: null
  final_activation: sigmoid
  dropout_p: 0.25
  n_flows: 10
  n_rgb: 1
  curriculum: false
  inputs: both
  weights: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
train:
  steps_per_epoch:
    train: 1000
    val: 200
    test: 20
  num_epochs: 10
  loss_weight_exp: 1.0
flow_generator:
  type: flow_generator
  flow_loss: MotionNet
  flow_max: 10
  input_images: 11
  flow_sparsity: false
  smooth_weight_multiplier: 1.0
  sparsity_weight: 0.0
  loss: MotionNet
  max: 5
  n_rgb: 11
  arch: TinyMotionNet
  weights: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220209_142218_flow_generator_train\lightning_checkpoints\epoch=0-step=999.ckpt
inference:
  directory_list:
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144036_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144307_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144421_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144544_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144738_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_144904_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145032_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145209_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145327_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145454_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145714_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_145939_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150104_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150321_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150726_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_150924_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151138_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151246_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_151927_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152207_video
  - D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA\220902_f94_152335_video
  ignore_error: true
  overwrite: true
  use_loaded_model_cfg: true
postprocessor:
  type: min_bout_per_behavior
  min_bout_length: 1
cmap: deepethogram
control_arrow_jump: 31
label_view_width: 31
prediction_opacity: 0.2
project:
  class_names:
  - background
  - fly
  - groom
  - landing_response
  config_file: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\project_config.yaml
  data_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\DATA
  labeler: null
  model_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models
  name: Tethered_Flight_pin
  path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram
  pretrained_path: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\pretrained_models
run:
  type: inference
  model: feature_extractor
  dir: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220905_143017_feature_extractor_inference
sequence:
  filter_length: 15
unlabeled_alpha: 0.1
vertical_arrow_jump: 3

[2022-09-05 14:30:17,459] INFO [__main__.feature_extractor_inference:481] Latent name used in HDF5 file: resnet18
[2022-09-05 14:30:17,475] INFO [deepethogram.data.augs.get_gpu_transforms:246] GPU transforms: {'train': Sequential(
  (0): ToFloat()
  (1): VideoSequential(
    (RandomHorizontalFlip_0): RandomHorizontalFlip(RandomHorizontalFlip(p=0.5, p_batch=1.0, same_on_batch=False))
    (RandomRotation_1): RandomRotation(RandomRotation(degrees=10, p=0.5, p_batch=1.0, same_on_batch=False, resample=bilinear, align_corners=True))
    (ColorJitter_2): ColorJitter(ColorJitter(brightness=0.25, contrast=0.1, saturation=0.1, hue=0.1, p=0.5, p_batch=1.0, same_on_batch=False))
    (RandomGrayscale_3): RandomGrayscale(RandomGrayscale(p=0.5, p_batch=1.0, same_on_batch=False))
  )
  (2): NormalizeVideo()
  (3): StackClipInChannels()
), 'val': Sequential(
  (0): ToFloat()
  (1): NormalizeVideo()
  (2): StackClipInChannels()
), 'test': Sequential(
  (0): ToFloat()
  (1): NormalizeVideo()
  (2): StackClipInChannels()
), 'denormalize': Sequential(
  (0): UnstackClip()
  (1): DenormalizeVideo()
)}
[2022-09-05 14:30:17,475] INFO [__main__.feature_extractor_inference:515] gpu_transform: Sequential(
  (0): ToFloat()
  (1): NormalizeVideo()
  (2): StackClipInChannels()
)
[2022-09-05 14:30:18,271] INFO [deepethogram.projects.get_weightfile_from_cfg:1079] loading specified weights: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:19,084] INFO [deepethogram.projects.get_weightfile_from_cfg:1079] loading specified weights: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:19,084] INFO [deepethogram.feature_extractor.train.build_model_from_cfg:220] feature extractor weightfile: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:19,162] INFO [deepethogram.utils.load_feature_extractor_components:630] loading component spatial from file D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:19,271] INFO [deepethogram.utils.load_feature_extractor_components:630] loading component flow from file D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:20,115] INFO [deepethogram.projects.get_weightfile_from_cfg:1079] loading specified weights: D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220209_142218_flow_generator_train\lightning_checkpoints\epoch=0-step=999.ckpt
[2022-09-05 14:30:20,115] INFO [deepethogram.utils.load_state:341] loading from checkpoint file D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220209_142218_flow_generator_train\lightning_checkpoints\epoch=0-step=999.ckpt...
[2022-09-05 14:30:20,146] INFO [deepethogram.utils.load_feature_extractor_components:630] loading component fusion from file D:\DeepEthogram_pin\Tethered_Flight_pin_deepethogram\models\220726_000617_feature_extractor_train\checkpoint.pt
[2022-09-05 14:30:20,178] INFO [__main__.feature_extractor_inference:545] best epoch from loaded file: -1
Traceback (most recent call last):
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\inference.py", line 548, in feature_extractor_inference
    thresholds = f['val']['metrics_by_threshold']['optimum'][best_epoch, :]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
**KeyError: "Unable to open object (object 'metrics_by_threshold' doesn't exist)"**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\inference.py", line 586, in <module>
    feature_extractor_inference(cfg)
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\inference.py", line 551, in feature_extractor_inference
    thresholds = f['threshold_curves']['val']['optimum'][best_epoch, :]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\zuidinga\Anaconda3\envs\deg\lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
**KeyError: "Unable to open object (object 'threshold_curves' doesn't exist)"**
[2022-09-05 14:30:21,037] INFO [deepethogram.gui.main.featureextractor_infer:462] Inference finished. If you see error messages above, inference did not complete successfully.
[2022-09-05 14:30:21,037] INFO [deepethogram.gui.main.featureextractor_infer:468] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-09-05 14:30:21,037] INFO [deepethogram.gui.main.project_loaded_buttons:175] Number finalized labels: 0
```

**Comment by Cumol** [comment]
Downgrade pytorch_lightning to 1.6.5

https://github.com/jbohnslav/deepethogram/issues/111#issuecomment-1237118674

**Comment by birtezuidinga** [comment]
> Downgrade pytorch_lightning to 1.6.5
> 
> [#111 (comment)](https://github.com/jbohnslav/deepethogram/issues/111#issuecomment-1237118674)

Thanks for the suggestion! It helped for the FlowGenerator indeed! 
Unfortunately not for my initial problem.

**Comment by birtezuidinga** [comment]
I found the reason for the errors. I did inference with the latest trained model, which I had apparently stopped before the training was finished completely. The classification_metrics.h5 file was very small (170 KB), and therefore probably did not include the metrics that the inference was searching for. Retraining and using the new model worked for me.
