### ISSUE TITLE
Progress_bar_refresh_rate error after flow generator training

### ISSUE THREAD

**Issue by sh00kti** [jbohnslav/deepethogram#117]
[
/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/deepethogram/data/utils.py:352: UserWarning: Only 3 records found...
  warnings.warn('Only {} records found...'.format(len(keys)))
[2022-09-19 22:13:05,164] INFO [__main__.flow_generator_train:67] Total trainable params: 1,951,784
[2022-09-19 22:13:05,233] INFO [deepethogram.projects.get_weightfile_from_cfg:1068] loading pretrained weights: /home/anuj/Desktop/ananya/ms_deepethogram/models/pretrained_models/200221_115158_TinyMotionNet/checkpoint.pt
reloading weights...
[2022-09-19 22:13:05,233] INFO [deepethogram.utils.load_state:341] loading from checkpoint file /home/anuj/Desktop/ananya/ms_deepethogram/models/pretrained_models/200221_115158_TinyMotionNet/checkpoint.pt...
[2022-09-19 22:13:05,243] INFO [__main__.get_metrics:364] key metric is SSIM
[2022-09-19 22:13:05,248] INFO [deepethogram.data.augs.get_gpu_transforms:246] GPU transforms: {'train': Sequential(
  (0): ToFloat()
  (1): VideoSequential(
    (RandomHorizontalFlip_0): RandomHorizontalFlip(RandomHorizontalFlip(p=0.5, p_batch=1.0, same_on_batch=False))
    (RandomRotation_1): RandomRotation(RandomRotation(degrees=10, p=0.5, p_batch=1.0, same_on_batch=False, resample=bilinear, align_corners=True))
    (ColorJitter_2): ColorJitter(ColorJitter(brightness=0.25, contrast=0.1, saturation=0.1, hue=0.1, p=0.5, p_batch=1.0, same_on_batch=False))
    (RandomGrayscale_3): RandomGrayscale(RandomGrayscale(p=0.5, p_batch=1.0, same_on_batch=False))
  )
  (2): NormalizeVideo()
  (3): StackClipInChannels()
), 'val': Sequential(
  (0): ToFloat()
  (1): NormalizeVideo()
  (2): StackClipInChannels()
), 'test': Sequential(
  (0): ToFloat()
  (1): NormalizeVideo()
  (2): StackClipInChannels()
), 'denormalize': Sequential(
  (0): UnstackClip()
  (1): DenormalizeVideo()
)}
[2022-09-19 22:13:05,248] INFO [deepethogram.base.__init__:95] scheduler mode: min
[2022-09-19 22:13:05,282] INFO [deepethogram.losses.get_regularization_loss:205] Regularization: L2_SP. Pretrained file: /home/anuj/Desktop/ananya/ms_deepethogram/models/pretrained_models/200221_115158_TinyMotionNet/checkpoint.pt alpha: 1e-05 beta: 0.001
[2022-09-19 22:13:05,289] INFO [deepethogram.flow_generator.losses.__init__:179] Using MotionNet Loss with settings: smooth_weights: [0.01, 0.02, 0.04, 0.08, 0.16] flow_sparsity: False sparsity_weight: 0.0
Traceback (most recent call last):
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/deepethogram/base.py", line 398, in get_trainer_from_cfg
    log_every_n_steps=1)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'reload_dataloaders_every_epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/deepethogram/flow_generator/train.py", line 374, in <module>
    flow_generator_train(cfg)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/deepethogram/flow_generator/train.py", line 78, in flow_generator_train
    trainer = get_trainer_from_cfg(cfg, lightning_module, stopper)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/deepethogram/base.py", line 413, in get_trainer_from_cfg
    log_every_n_steps=1)
  File "/home/anuj/miniconda3/envs/deg/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'progress_bar_refresh_rate'
[2022-09-19 22:13:05,619] INFO [deepethogram.gui.main.flow_train:353] Training finished. If you see error messages above, training did not complete successfully.
[2022-09-19 22:13:05,619] INFO [deepethogram.gui.main.flow_train:359] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-09-19 22:13:05,620] INFO [deepethogram.gui.main.project_loaded_buttons:175] Number finalized labels: 0
[2022-09-19 22:16:36,869] INFO [deepethogram.gui.main.log_idle:151] User has been idle for 60.0 seconds...
[2022-09-19 22:16:50,342] INFO [deepethogram.gui.main.user_did_something:138] User restarted labeling

**Comment by jbwallace123** [comment]
Seems to be a pytorch version error. I switched to version 1.5.10 and it worked properly.

**Comment by sh00kti** [comment]
Thank you!
But now there is a different error:

**Comment by jbwallace123** [comment]
I'm trouble shooting this myself so I can keep this updated. I ran into the same issue. If we look at his google colab notebook output, the version of pytorch used there was 1.11. 0 so I'm starting at the original dependency (1.5.10) and working my way up.  I'll keep you updated as I figure this out myself.

**Comment by AnanyaPassi-prog** [comment]
Thank you very much for this helpful thread! 

I tried all these steps and faced very similar issues. 

After doing **pip install pytorch_lightning==1.6.5 with torch==1.11.0** , I got the following error 

**ModuleNotFoundError : No module named PIL**

**Comment by AnanyaPassi-prog** [comment]
Thank you very much for this! 

I was facing the same issues and thus tried all the steps listed above. 

After doing,  pip install pytorch_lightning==1.6.5 with torch==1.11.0, I got an error that PIL was absent. So, I installed PIL using conda. 

However, I am now getting this error: **pytorch_lightning.utilities.exceptions.MisconfigurationException: GPUAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].**

Please do let me know what you think. 

Thank you very much for this thread!

**Comment by jbwallace123** [comment]
@AnanyaPassi-prog This seems like a different issue and it may be that your GPU isn't configured properly. The trainer cannot run on a CPU only system. I would make sure your drivers are updated and you have your proper gcc and cuda installed for your GPU on your machine.

**Comment by AnanyaPassi-prog** [comment]
@jbwallace123 Thank you very much for your speedy response! 

What versions of gcc and coda could you recommend?

**Comment by sh00kti** [comment]
> I'm trouble shooting this myself so I can keep this updated. I ran into the same issue. If we look at his google colab notebook output, the version of pytorch used there was 1.11. 0 so I'm starting at the original dependency (1.5.10) and working my way up. Update: I have found that updating pytorch_lightning helps as well to: pip install pytorch_lightning==1.6.5 with torch==1.11.0

I tried that, and I did make some progress. Although I am now getting an error that says that CUDA  ran out of memory;

**RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 3.82 GiB total capacity; 2.62 GiB already allocated; 97.44 MiB free; 2.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.**

I tried putting `torch.cuda.set_per_process_memory_fraction(0.5)` (to reduce memory taken up by the process) at the beginning of deepethogram/flow_generator/train.py but it did not seem to do anything, and `torch.cuda.max_split_size_mb` does not exist.

**Comment by jbwallace123** [comment]
@AnanyaPassi-prog gcc and cuda versions are specific to OS and GPU so not really sure it's wise for me to recommend anything specific. I'm running linux and using gcc/6.2.0 with cuda/10.2 with python/3.7.4 but again, that's specific to the hardware I'm using.

**Comment by AnanyaPassi-prog** [comment]
Thank you very much for this!

**Comment by AnanyaPassi-prog** [comment]
Hi @jbwallace123 . Thank you very much for your previous help!

I am not  sure if I am using the correct versions. Could you please recommend which cuda version I should use?

I am on Linux (Ubuntu: 20.04.5 LTS) and have the NVIDIA 3060 GPU. 

Previously, I was using cuda V10.1.243 and gcc version 9.4.0. 

Thanks you for your previous help :)

**Comment by PaulineEmilia** [comment]
Hi @AnanyaPassi-prog, I am facing the same MisconfigurationError after updating the pytorch-lightning and torch versions. Did you find a solution to this? 
Thanks for your help!

**Comment by PaulineEmilia** [comment]
Hi @AnanyaPassi-prog, I am facing the same MisconfigurationException after updating the pytorch_lightning and torch versions. Did you find a solution to this?

Thanks for your help!
