### ISSUE TITLE
flow generator attribute error

### ISSUE THREAD

**Issue by jbwallace123** [jbohnslav/deepethogram#118]
I seem to continue to get an error when attempting to run flow_generator. It seems that I receive an error when it attempts to open the video that then results in the following series of errors (please see below). Any idea of what could possibly be the issue? The code seems to be working properly as I have been able to successfully run the test data set. My video type is .AVI and I am attempting to convert to hdf5 but am having issues with that as well. I'm not sure if this has to do with my video quality/dropped frames. 

Thanks in advance.

AttributeError: Caught AttributeError in DataLoader worker process 9.
Original Traceback (most recent call last):
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/deepethogram/data/datasets.py", line 342, in __getitem__
    image = reader[i + start_frame]
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/vidio/read.py", line 70, in __getitem__
    return self.read(*args, **kwargs)
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/vidio/read.py", line 115, in read
    raise ValueError('error decoding frame {} from video {}'.format(framenum, self.filename))
ValueError: error decoding frame 53999 from video /home/jbw25/Kim_reaching_import_deepethogram/DATA/2021-01-20 16-00-30-C/2021-01-20 16-00-30-C.AVI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/deepethogram/data/datasets.py", line 415, in __getitem__
    return self.dataset[index]
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/jbw25/deepethogram/lib/python3.7/site-packages/deepethogram/data/datasets.py", line 344, in __getitem__
    image = self._zeros_image.copy().transpose(1, 2, 0)
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by jbwallace123** [comment]
Removed dropped frames then converted to .h5 then, code ran perfectly.
