### ISSUE TITLE
RuntimeError: The expanded size of the tensor (5) must match the existing size (4) .... 

### ISSUE THREAD

**Issue by jbwallace123** [jbohnslav/deepethogram#123]
I'm beginning to train by running the feature extractor. I then receive the following error: 

RuntimeError: The expanded size of the tensor (5) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [32, 5].  Tensor sizes: [4]

Has anyone run into this issue? 

Thanks in advance!

**Comment by amorsi1** [comment]
Hi! Did you find a solution to this problem? I'm running the program in a docker environment and am getting the following error when I try to train the feature extractor:

`Epoch 0:   0%|                                                                                         | 0/2000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/deepethogram/deepethogram/feature_extractor/train.py", line 646, in <module>
    feature_extractor_train(cfg)
  File "/app/deepethogram/deepethogram/feature_extractor/train.py", line 182, in feature_extractor_train
    trainer.fit(lightning_module)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 207, in advance
    self.optimizer_idx,
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    using_lbfgs=is_lbfgs,
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/optim/adam.py", line 100, in step
    loss = closure()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 333, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/app/deepethogram/deepethogram/feature_extractor/train.py", line 350, in training_step
    images, outputs = self(batch, 'train')
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/deepethogram/deepethogram/feature_extractor/train.py", line 507, in forward
    outputs = self.model(gpu_images)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/deepethogram/deepethogram/feature_extractor/models/hidden_two_stream.py", line 227, in forward
    spatial_features = self.spatial_classifier(RGB)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 1.  Target sizes: [32, 5].  Tensor sizes: [6]`

**Comment by jbwallace123** [comment]
I'm so sorry, it's been quite sometime since I have run this code. I do remember that I had to do a lot of preprocessing of my video to get it in the right format for deepethogram. I had some dropped frames that caused indexing errors that were not obvious to the eye and a codec issue for the video type. I also had to covert to hdf5 which helped immensely.

You can see the preprocessing that worked for me on my GitHub repo below .. apologies it is not commented well as this was just a quick fix for my SLURM workflow.
 
https://github.com/jbwallace123/DeepEthogram_file_set_up 

Good luck!

**Comment by amorsi1** [comment]
Hi! Thanks the quick response and linking some of your work. After some digging i found that my tensor size error was coming from the fact that I hadn't populated the DATA folder of my project correctly.

Specifically my error was not importing the video files through the GUI and instead just dropping them into the folder. The directory for each video file had the video file and the labels.csv file (all named appropriately) but lacked the record.yaml and project.yaml files that were added when they were imported properly.

**Comment by hummuscience** [comment]
This error (in my case) was caused by a mismatch between the number of columns/labels in the labels file and the behaviors listed in the project_config.yaml file
