### ISSUE TITLE
Error during flow_generator training "TypeError: __init__() got an unexpected keyword argument"

### ISSUE THREAD

**Issue by Thomaswong123** [jbohnslav/deepethogram#127]
Dear deg dev,

Hello, I have just installed deg to try it using the gui. This appear when I try to train the flow_generator. I believe it is related to the change in pytorch lighting as you have updated base.py to show this error. May I know how can I fix this issue? Many Thanks.

`Traceback (most recent call last):
  File "c:\users\lab80\deepethogram\deepethogram\base.py", line 398, in get_trainer_from_cfg
    log_every_n_steps=1)
  File "D:\anaconda\envs\deg\lib\site-packages\pytorch_lightning-1.8.0.post1-py3.7.egg\pytorch_lightning\utilities\argparse.py", line 340, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'reload_dataloaders_every_epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\lab80\deepethogram\deepethogram\flow_generator\train.py", line 374, in <module>
    flow_generator_train(cfg)
  File "c:\users\lab80\deepethogram\deepethogram\flow_generator\train.py", line 78, in flow_generator_train
    trainer = get_trainer_from_cfg(cfg, lightning_module, stopper)
  File "c:\users\lab80\deepethogram\deepethogram\base.py", line 413, in get_trainer_from_cfg
    log_every_n_steps=1)
  File "D:\anaconda\envs\deg\lib\site-packages\pytorch_lightning-1.8.0.post1-py3.7.egg\pytorch_lightning\utilities\argparse.py", line 340, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'progress_bar_refresh_rate'`

**Comment by Ivy-ZOU** [comment]
Has the problem been solved?
I have exactly the same problem as you......

**Comment by giannottigiuseppe** [comment]
try install pytorch-lightning==1.5.10

**Comment by benjaws** [comment]
@giannottigiuseppe Thank you, I had the same error, it solved the issue.
