### ISSUE TITLE
Cant open deepethogram "'OmegaConf' has no attribute 'to_yaml'"

### ISSUE THREAD

**Issue by BEETeamLMG** [jbohnslav/deepethogram#128]
Hello everyone.

I'm trying to use deepethogram to classify fish interactions.

I installed using the steps on docs in "Installing from source".
Then tried to startup.

First got this problem. I uninstalled hydra-core as asked by the terminal.
```
(deg) C:\Users\BEE Team\deepethogram>python -m deepethogram
Traceback (most recent call last):
  File "C:\Users\Public\new\envs\deg\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Public\new\envs\deg\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Public\new\envs\deg\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\BEE Team\deepethogram\deepethogram\__init__.py", line 12, in <module>
    raise ValueError('Hydra installation found. Please run pip uninstall hydra-core: {}'.format(spec))
ValueError: Hydra installation found. Please run pip uninstall hydra-core: ModuleSpec(name='hydra', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000022182FA0FC8>, origin='C:\\Users\\Public\\new\\envs\\deg\\lib\\site-packages\\hydra\\__init__.py', submodule_search_locations=['C:\\Users\\Public\\new\\envs\\deg\\lib\\site-packages\\hydra'])

(deg) C:\Users\BEE Team\deepethogram>pip uninstall hydra-core
Found existing installation: hydra-core 0.11.3
Uninstalling hydra-core-0.11.3:
  Would remove:
    c:\users\public\new\envs\deg\lib\site-packages\hydra\*
    c:\users\public\new\envs\deg\lib\site-packages\hydra_core-0.11.3.dist-info\*
    c:\users\public\new\envs\deg\lib\site-packages\tests\*
Proceed (Y/n)? y
  Successfully uninstalled hydra-core-0.11.3
```

Then got this issue, and don't know how to solve it:
```
(deg) C:\Users\BEE Team\deepethogram>python -m deepethogram
[2022-11-28 10:47:59,069] INFO [deepethogram.gui.main.setup_gui_cfg:1268] CWD: C:\Users\BEE Team\deepethogram
Traceback (most recent call last):
  File "C:\Users\Public\new\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Public\new\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\BEE Team\deepethogram\deepethogram\__main__.py", line 10, in <module>
    entry()
  File "C:\Users\BEE Team\deepethogram\deepethogram\gui\main.py", line 1291, in entry
    run()
  File "C:\Users\BEE Team\deepethogram\deepethogram\gui\main.py", line 1278, in run
    cfg = setup_gui_cfg()
  File "C:\Users\BEE Team\deepethogram\deepethogram\gui\main.py", line 1269, in setup_gui_cfg
    log.info('Configuration used: {}'.format(OmegaConf.to_yaml(cfg)))
AttributeError: type object 'OmegaConf' has no attribute 'to_yaml'
```

Anyone knows how to solve it?

Thank you for your time

**Comment by BEETeamLMG** [comment]
`pip install --upgrade omegaconf`
Solver the issue.
