### ISSUE TITLE
Training Flow Generator

### ISSUE THREAD

**Issue by lkoch97** [jbohnslav/deepethogram#142]
Dear deepethogram team,

when I try to train the flow generator I get the following error messages:

TypeError: __init__() got an unexpected keyword argument 'gpus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lukas\anaconda3\envs\deg\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lukas\anaconda3\envs\deg\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lukas\anaconda3\envs\deg\lib\site-packages\deepethogram\flow_generator\train.py", line 374, in <module>
    flow_generator_train(cfg)
  File "C:\Users\lukas\anaconda3\envs\deg\lib\site-packages\deepethogram\flow_generator\train.py", line 78, in flow_generator_train
    trainer = get_trainer_from_cfg(cfg, lightning_module, stopper)
  File "C:\Users\lukas\anaconda3\envs\deg\lib\site-packages\deepethogram\base.py", line 401, in get_trainer_from_cfg
    trainer = pl.Trainer(gpus=[cfg.compute.gpu_id],
  File "C:\Users\lukas\anaconda3\envs\deg\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)

I assume this has something to do with the most recent Pytorch version that I have installed, but using older versions has not solved the problem yet. Any hint on how to fix this issue is very welcome, thank you!
Lukas

**Comment by kushalkolar** [comment]
Ran into this problem as well, I think a lot of stuff is broken with the newer versions of not just torch.

I have a set of instructions from a year ago when it was working, might be helpful for you. Linux & pip specific, I don't mess with conda or other OSs

https://github.com/kushalkolar/deg-installation-instructions

@jbohnslav do you have someone that can take over maintaining this project? It's a really useful tool and setting up a CI pipeline on it will help it live on :)

**Comment by clewis7** [comment]
@lkoch97 

Here's a pip freeze in an environment that I setup and got DEG working on, Linux and CUDA v12 on a RTX 3090

[deg_requirements.txt](https://github.com/jbohnslav/deepethogram/files/11580482/deg_requirements.txt)

**Comment by lkoch97** [comment]
Thank you very much for the help, I was trying to get it working on Windows, but will try again with Linux.
