### ISSUE TITLE
get_buffer() failed

### ISSUE THREAD

**Issue by ycwei0321** [jbohnslav/deepethogram#146]
2023-07-20 17:12:42,178] INFO [deepethogram.gui.main.log_idle:151] User has been idle for 60.0 seconds...
Epoch 0:  83%|███████████████████████████████████████▏       | 1000/1200 [38:27<07:41,  2.31s/it, loss=0.0233, v_num=0][h264 @ 000001e28500e6c0] [[h264 @ 000001d667bd2480] ERROR:0@0.016] global cap_ffmpeg_impl.hpp:1278 open Could not open codec h264, error: -12
get_buffer() failed
[h264 @ 000001bffee5f8c0] [decode_slice_header error
ERROR:0@0.016] global cap_ffmpeg_impl.hpp:1286 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[h264 @ 000001e28500e6c0] Error splitting the input into NAL units.
[h264 @ 000001d667bd2480] thread_get_buffer() failed
no frame!
[h264 @ 000001bffef9e840] [h264 @ 000001e28500e6c0] Error splitting the input into NAL units.
decode_slice_header error
[h264 @ 000001d667bd2a40] [h264 @ 000001e28500e6c0] [h264 @ 000001bffeddb7c0] Error splitting the input into NAL units.
no frame!
Error splitting the input into NAL units.
[h264 @ 000001d667c5ec00] [h264 @ 000001bffeddbc40] Error splitting the input into NAL units.
[ERROR:0@0.031] global cap_ffmpeg_impl.hpp:1278 open Could not open codec h264, error: -1
Error splitting the input into NAL units.
[[h264 @ 000001e286737b00] [h264 @ 000001d667c5f080] ERROR:0@0.031] global cap_ffmpeg_impl.hpp:1286 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
get_buffer() failed
[h264 @ 000001bffef93280] decode_slice_header error
[h264 @ 000001e286737b00] Error splitting the input into NAL units.
[h264 @ 000001d667c5f080] thread_get_buffer() failed
no frame!
[h264 @ 000001bffee5f8c0] [h264 @ 000001e286737b00] get_buffer() failed
decode_slice_header error
Process Process-12:
[h264 @ 000001bffee5f8c0] [h264 @ 000001e286737b00] thread_get_buffer() failed
no frame!
[h264 @ 000001bffee5f8c0] decode_slice_header error
[h264 @ 000001e284e48cc0] [h264 @ 000001bffee5f8c0] get_buffer() failed
no frame!
[h264 @ 000001e284e48cc0] thread_get_buffer() failed
[h264 @ 000001e284e48cc0] decode_slice_header error
[h264 @ 000001e284e48cc0] no frame!
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000122a944b7c0] error reading header
[h264 @ 000001e284e49700] Error splitting the input into NAL units.
Traceback (most recent call last):
  File "D:\Users\winshah\anaconda3\envs\vole\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\_utils\worker.py", line 322, in _worker_loop
    data_queue.put((idx, data))
  File "D:\Users\winshah\anaconda3\envs\vole\lib\multiprocessing\queues.py", line 94, in put
    self._start_thread()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\multiprocessing\queues.py", line 177, in _start_thread
    self._thread.start()
[h264 @ 000001e28500e6c0]   File "D:\Users\winshah\anaconda3\envs\vole\lib\threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
decode_slice_header error
[h264 @ 000001e28500e6c0] no frame!
[h264 @ 000001e284e48cc0] get_buffer() failed
[h264 @ 000001e284e48cc0] thread_get_buffer() failed
[h264 @ 000001e284e48cc0] decode_slice_header error
[h264 @ 000001e284e48cc0] no frame!
[h264 @ 000001e284e49140] get_buffer() failed
[h264 @ 000001e284e49140] thread_get_buffer() failed
[h264 @ 000001e284e49140] decode_slice_header error
[h264 @ 000001e284e49140] no frame!
[h264 @ 000001e284e49700] decode_slice_header error
[h264 @ 000001e284e49700] no frame!
[h264 @ 000001e284e49cc0] Could not allocate memory
[h264 @ 000001e284e49cc0] h264_slice_header_init() failedget_buffer() failed
[h264 @ 000001e2d29fac00] thread_get_buffer() failed
[h264 @ 000001e2d29fac00] decode_slice_header error
[h264 @ 000001e2d29fac00] no frame!
[h264 @ 000001e2d29fc780] decode_slice_header error
[h264 @ 000001e2d29fc780] no frame!
[h264 @ 000001e2d29f99c0] get_buffer() failed
[h264 @ 000001e2d29f99c0] thread_get_buffer() failed
[h264 @ 000001e2d29f99c0] decode_slice_header error
[h264 @ 000001e2d29f99c0] no frame!
[h264 @ 000001e2d29f9e80] get_buffer() failed
[h264 @ 000001e2d29f9e80] thread_get_buffer() failed
[h264 @ 000001e2d29f9e80] decode_slice_header error
[h264 @ 000001e2d29f9e80] no frame!
[h264 @ 000001e2d29fb0c0] decode_slice_header error
[h264 @ 000001e2d29fb0c0] no frame!
[h264 @ 000001e2d29fe2c0] get_buffer() failed
[h264 @ 000001e2d29fe2c0] thread_get_buffer() failed
[h264 @ 000001e2d29fe2c0] decode_slice_header error
[h264 @ 000001e2d29fe2c0] no frame!
[h264 @ 000001e2d29fc300] Error splitting the input into NAL units.
[h264 @ 000001e2d29fb540] get_buffer() failed
[h264 @ 000001e2d29fb540] thread_get_buffer() failed
[h264 @ 000001e2d29fb540] decode_slice_header error
[h264 @ 000001e2d29fb540] no frame!
[h264 @ 000001e2d29fbe40] get_buffer() failed
[h264 @ 000001e2d29fbe40] thread_get_buffer() failed
[h264 @ 000001e2d29fbe40] decode_slice_header error
[h264 @ 000001e2d29fbe40] no frame!
[h264 @ 000001e2d29f9540] Error splitting the input into NAL units.
[h264 @ 000001e2d29fcc00] Could not allocate memory
[h264 @ 000001e2d29fcc00] h264_slice_header_init() failedget_buffer() failed
[h264 @ 000001e2d29f99c0] thread_get_buffer() failed
[h264 @ 000001e2d29f99c0] decode_slice_header error
[h264 @ 000001e2d29f99c0] no frame!
[h264 @ 000001e2d29f9e80] get_buffer() failed
[h264 @ 000001e2d29f9e80] thread_get_buffer() failed
[h264 @ 000001e2d29f9e80] decode_slice_header error
[h264 @ 000001e2d29f9e80] no frame!
[h264 @ 000001e2d29fb0c0] get_buffer() failed
[h264 @ 000001e2d29fb0c0] thread_get_buffer() failed
[h264 @ 000001e2d29fb0c0] decode_slice_header error
[h264 @ 000001e2d29fb0c0] no frame!
[h264 @ 000001e2d29fe2c0] Error splitting the input into NAL units.
[h264 @ 000001e2d29fc300] Error splitting the input into NAL units.
[h264 @ 000001e2d29fb540] get_buffer() failed
[h264 @ 000001e2d29fb540] thread_get_buffer() failed
[h264 @ 000001e2d29fb540] decode_slice_header error
[h264 @ 000001e2d29fb540] no frame!
[h264 @ 000001e2d29fbe40] get_buffer() failed
[h264 @ 000001e2d29fbe40] thread_get_buffer() failed
[h264 @ 000001e2d29fbe40] decode_slice_header error
[h264 @ 000001e2d29fbe40] no frame!
[h264 @ 000001e2d29f9540] Error splitting the input into NAL units.
[h264 @ 000001e2d29fcc00] Could not allocate memory
[h264 @ 000001e2d29fcc00] h264_slice_header_init() failed[ERROR:0@0.645] global cap_ffmpeg_impl.hpp:1278 open Could not open codec h264, error: -1
[ERROR:0@0.645] global cap_ffmpeg_impl.hpp:1278 open Could not open codec h264, error: -12
[ERROR:0@0.645] global cap_ffmpeg_impl.hpp:1286 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ERROR:0@0.645] global cap_ffmpeg_impl.hpp:1286 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[h264 @ 0000019c8b9fde00] get_buffer() failed
[h264 @ 0000019c8b9fde00] thread_get_buffer() failed
[h264 @ 0000019c8b9fde00] decode_slice_header error
[h264 @ 0000019c8b9fde00] no frame!
[h264 @ 0000019cd91d2240] get_buffer() failed
[h264 @ 000001860674b2c0] [h264 @ 0000019cd91d2240] Could not allocate memory
thread_get_buffer() failed
[h264 @ 000001860674b2c0] h264_slice_header_init() failed[h264 @ 0000019cd91d2240] decode_slice_header error
[h264 @ 0000019cd91d2240] no frame!
Traceback (most recent call last):
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\winshah\anaconda3\envs\vole\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\winshah\anaconda3\envs\vole\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\deepethogram\flow_generator\train.py", line 374, in <module>
    flow_generator_train(cfg)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\deepethogram\flow_generator\train.py", line 79, in flow_generator_train
    trainer.fit(lightning_module)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\base.py", line 146, in run
    self.on_advance_end()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 242, in on_advance_end
    self._run_validation()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 337, in _run_validation
    self.val_loop.run()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 86, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\loops\utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 199, in __iter__
    self.prefetching(self.prefetch_batches)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 258, in prefetching
    self._fetch_next_batch()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "D:\Users\winshah\anaconda3\envs\vole\lib\site-packages\torch\utils\data\dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 12092) exited unexpectedly
Epoch 0:  83%|████████▎ | 1001/1200 [39:46<07:54,  2.38s/it, loss=0.0233, v_num=0]
                                                                                                                       [2023-07-20 17:51:47,995] INFO [deepethogram.gui.main.flow_train:353] Training finished. If you see error messages above, training did not complete successfully.
[2023-07-20 17:51:47,995] INFO [deepethogram.gui.main.flow_train:359] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-07-20 17:51:48,547] INFO [deepethogram.gui.main.project_loaded_buttons:175] Number finalized labels: 0

Hello, I'm trying to run the deepethogram on local computer. However, when I click the FlowGenerator Train, it gave me above errors. Can someone give me some suggestions on this? How can I fix it? Thanks.

**Comment by ycwei0321** [comment]
this issue can be solved by installing "h264 ".
