### ISSUE TITLE
Feature Extractor Training Error

### ISSUE THREAD

**Issue by banningjoe** [jbohnslav/deepethogram#16]
Hi there,

I've just trained the flow generator, and am moving on to training the feature extractor. 
I'm training on windows 10. 

Every time I try and train the flow generator I get the following error.

  0%|                                                                                                                                                                        | 0/20 [00:00<?, ?it/s]
FPS: 16.52:   0%|                                                                                                                                                            | 0/20 [00:15<?, ?it/s]
FPS: 16.52:   5%|███████▍                                                                                                                                            | 1/20 [00:15<04:50, 15.30s/it]
  0%|                                                                                                                                                                      | 0/1000 [02:51<?, ?it/s]
Traceback (most recent call last):
  File "c:\users\jb\anaconda3\envs\deg\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jb\anaconda3\envs\deg\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 675, in <module>
    main()
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\hydra\main.py", line 20, in decorated_main
    run_hydra(
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\hydra\_internal\utils.py", line 171, in run_hydra
    hydra.run(
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\hydra\_internal\hydra.py", line 82, in run
    return run_job(
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 56, in main
    model = train_from_cfg(cfg)
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 203, in train_from_cfg
    spatial_classifier = train(spatial_classifier,
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 451, in train
    metrics = speedtest(loader, model, metrics, steps_per_epoch['test'], device=device, dali=dali)
  File "c:\users\jb\anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\train.py", line 668, in speedtest
    t.set_description('FPS: {:.2f}'.format(1 / time_per_image))
ZeroDivisionError: float division by zero

Let me know if any other info is needed in order to understand the issue.

Best,
Joe Banning

**Comment by jbohnslav** [comment]
Fixed with commit 24f83d2. If you follow in the installation instructions for "install from source", the bug should be fixed.

**Comment by banningjoe** [comment]
Wonderful, thanks!
