### ISSUE TITLE
new (wannabe) user - DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by kipkeller** [jbohnslav/deepethogram#160]
Tried various versions of the git instructions without luck. Currently trying the beta upgrade:
python -m deepethogram
gives:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\wehr\deepethogram\deepethogram\__main__.py", line 1, in <module>
    from deepethogram.gui.main import entry
  File "c:\Users\wehr\deepethogram\deepethogram\gui\main.py", line 13, in <module>
    from PySide2 import QtCore, QtWidgets, QtGui
ImportError: DLL load failed: The specified module could not be found.

here are my included packages:
# packages in environment at C:\ProgramData\anaconda3\envs\deg:
#
# Name                    Version                   Build  Channel
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h2bbff1b_1003
ca-certificates           2024.2.2             h56e8100_0    conda-forge
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.15.1           py37h2bbff1b_3
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cryptography              38.0.2           py37h953a470_1    conda-forge
cudatoolkit               10.2.89              h74a9793_1
cycler                    0.11.0                   pypi_0    pypi
deepethogram              0.1.4                    pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
h5py                      2.10.0                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.6.12                   pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
lightning-utilities       0.10.1                   pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
multidict                 6.0.5                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37hca35cd5_3
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python-headless    4.9.0.80                 pypi_0    pypi
opencv-transforms         0.0.3.post2              pypi_0    pypi
openssl                   3.0.13               h2bbff1b_0
packaging                 23.2                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 23.0.0           py37haa95532_0
pyparsing                 3.1.1                    pypi_0    pypi
pyside2                   5.15.2.1                 pypi_0    pypi
pysocks                   1.7.1                    py37_1
python                    3.7.1                h33f27b4_4
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.13.1              py3.7_cpu_0    pytorch
pytorch-lightning         1.9.5                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                69.0.3                   pypi_0    pypi
shiboken2                 5.15.2.1                 pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.44.2               hcfcfb64_0    conda-forge
tbb                       2021.8.0             h59b6b97_0
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torchaudio                0.13.1                 py37_cpu    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.14.1                 py37_cpu    pytorch
tqdm                      4.66.1                   pypi_0    pypi
typing_extensions         4.4.0            py37haa95532_0
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.0.7                    pypi_0    pypi
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vidio                     0.0.4                    pypi_0    pypi
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py37haa95532_0
xz                        5.4.5                h8cc25b3_0
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

Thanks!

**Comment by jihirmas** [comment]
Could you fix it? I am having the same problem

**Comment by HOLGUINsantiago** [comment]
Same error. 3 days trying to install but all combinations of versions have problems.... Any idea?
