### ISSUE TITLE
Issue Running Sequence Training

### ISSUE THREAD

**Issue by banningjoe** [jbohnslav/deepethogram#17]
Hi there,

After running the feature extractor successfully on two videos, I am now trying to run my sequence training.

However, I get the following error:

Traceback (most recent call last):
  File "C:\Users\JB\Anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 155, in <module>
    main()
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\hydra\main.py", line 24, in decorated_main
    strict=strict,
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\hydra\_internal\utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\hydra\_internal\hydra.py", line 86, in run
    job_subdir_key=None,
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 41, in main
    model = train_from_cfg(cfg)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 56, in train_from_cfg
    neg=dataloaders['neg'])
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 146, in build_model_from_cfg
    nonlinear_classification=seq.nonlinear_classification)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\models\tgm.py", line 291, in __init__
    bias = torch.nn.Parameter(bias)
  File "C:\Users\JB\Anaconda3\envs\deg\lib\site-packages\torch\nn\parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not numpy.ndarray

Thoughts?

Best,
Joe

**Comment by jbohnslav** [comment]
Crap! Bug introduced fixing a different one. Should be fixed with 10cd1a8.
