### ISSUE TITLE
Training Sequence Model Error

### ISSUE THREAD

**Issue by sonjablumenstock** [jbohnslav/deepethogram#20]
Hi,
my compliments on the software, it is a great tool and very straightforward to use. I've run into the following error when I try to train the sequence model using the GUI (after running inference on my videos and getting the outputs.h5 files).

TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not numpy.ndarray

Am I missing something here?
Thanks,
Sonja

**Comment by jbohnslav** [comment]
Can you post the full error message? I think it might have to do with the bias initialization, but I need to see the whole thing.

**Comment by sonjablumenstock** [comment]
Of course, thank you for the quick reply. Here it is:

```
Traceback (most recent call last):
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 155, in <module>
    main()
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\main.py", line 24, in decorated_main
    strict=strict,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\_internal\utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\_internal\hydra.py", line 86, in run
    job_subdir_key=None,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 41, in main
    model = train_from_cfg(cfg)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 56, in train_from_cfg
    neg=dataloaders['neg'])
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 146, in build_model_from_cfg
    nonlinear_classification=seq.nonlinear_classification)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\models\tgm.py", line 291, in __init__
    bias = torch.nn.Parameter(bias)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\torch\nn\parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not numpy.ndarray
```

**Comment by jbohnslav** [comment]
Hi Sonja,

This should've been fixed with 10cd1a8. I haven't updated the pip package with this fix yet. Could you install from source and see if that fixes it?

**Comment by sonjablumenstock** [comment]
Hi,

I reinstalled deepethogram, but now it seems like my GPU is not engaged any more (it was working fine before).

Here's the new error:
```
Traceback (most recent call last):
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 155, in <module>
    main()
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\main.py", line 24, in decorated_main
    strict=strict,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\_internal\utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\_internal\hydra.py", line 86, in run
    job_subdir_key=None,
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 41, in main
    model = train_from_cfg(cfg)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1.post1-py3.7.egg\deepethogram\sequence\train.py", line 48, in train_from_cfg
    if device != 'cpu': torch.cuda.set_device(device)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    device = _get_device_index(device)
  File "C:\Users\blumenstock\AppData\Local\Continuum\anaconda3\envs\deg\lib\site-packages\torch\cuda\_utils.py", line 31, in _get_device_index
    raise ValueError('Expected a cuda device, but got: {}'.format(device))
ValueError: Expected a cuda device, but got: cpu
```

**Comment by jbohnslav** [comment]
Hmm, it could be that your PyTorch installation doesn't work anymore. Can you open up a python interpreter in the correct Anaconda environment and enter:
```python
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())
```

**Comment by sonjablumenstock** [comment]
Hi Jim,
I manually reinstalled PyTorch in my deg environment (with the cudatoolkit matching my cuda version) and now deepethogram seems to be happily training the sequence model :).
(maybe of interest for others, because it's NOT a general issue: in my case, I noticed that I had run low on space on my disk, maybe that's why PyTorch wasn't completely installed with my new deepethogram installation)

Thanks a lot for your help!

**Comment by jbohnslav** [comment]
Glad it worked out! Sorry for the issues.
