### ISSUE TITLE
IndexError: index 3526 is out of bounds for axis 0 with size 3493 

### ISSUE THREAD

**Issue by KubraE** [jbohnslav/deepethogram#24]
Hi, after training flow generator without an issue, I tried to train the feature extractor by using GUI, however I got the below error that complains about indexes. Do you know why I am getting this error and how can i fix it?
```
[2020-11-25 10:20:26,718][deepethogram.gui.main][INFO] - Number finalized labels: 3
[2020-11-25 10:28:54,231][deepethogram.gui.main][INFO] - User restarted labeling
[2020-11-25 10:28:59,904][deepethogram.gui.main][INFO] - feature extractor train called with args: ['python', '-m', 'deepethogram.feature_extractor.train', 'project.config_file=/projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/project_config.yaml', 'feature_extractor.weights=/projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/checkpoint.pt', 'flow_generator.weights=/projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/201125_014532_flow_generator_train_None/checkpoint.pt']
[2020-11-25 10:29:03,577][__main__][INFO] - cwd: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/201125_102903_feature_extractor_train_None
[2020-11-25 10:29:03,578][__main__][INFO] - configuration used ~~~~~
[2020-11-25 10:29:03,582][__main__][INFO] - augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  normalization:
    N: 3675258880
    mean:
    - 0.17030547916444036
    - 0.011406822383848917
    - 0.6321989001349098
    std:
    - 0.08265920461495736
    - 0.05720523456998572
    - 0.166993562276202
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
compute:
  batch_size: 32
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  num_workers: 2
feature_extractor:
  arch: resnet18
  curriculum: true
  dropout_p: 0.9
  final_activation: sigmoid
  fusion: average
  inputs: both
  n_flows: 10
  n_rgb: 1
  sampler: null
  sampling_ratio: null
  weight_decay: 0
  weights: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/checkpoint.pt
flow_generator:
  arch: TinyMotionNet
  flow_loss: MotionNet
  flow_max: 10
  flow_sparsity: false
  input_images: 11
  loss: MotionNet
  max: 10
  n_rgb: 11
  smooth_weight_multiplier: 1.0
  sparsity_weight: 0.0
  type: flow_generator
  weights: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/201125_014532_flow_generator_train_None/checkpoint.pt
notes: null
preset: null
project:
  class_names:
  - background
  - myclassnames
  - ...
  config_file: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/project_config.yaml
  data_path: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/DATA
  labeler: null
  model_path: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models
  name: proj1-rec26
  path: /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram
reload:
  latest: false
  overwrite_cfg: false
  weights: null
run:
  model: feature_extractor
  type: train
sequence:
  filter_length: 15
split:
  file: null
  reload: true
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
train:
  early_stopping_begins: 0
  loss_weight_exp: 1.0
  lr: 0.0001
  milestones:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  min_lr: 5.0e-07
  num_epochs: 1000
  patience: 5
  reduction_factor: 0.1
  scheduler: plateau
  steps_per_epoch:
    test: 20
    train: 1000
    val: 1000
  stopping_type: learning_rate
  viz: true
  weight_loss: true

/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/flow_generator/models/TinyMotionNet.py:49: UserWarning: ignoring flow div value of 10: setting to 1 instead
  warnings.warn('ignoring flow div value of {}: setting to 1 instead'.format(flow_div))
[2020-11-25 10:29:03,920][deepethogram.projects][INFO] - loading specified weights
[2020-11-25 10:29:03,920][__main__][INFO] - loading flow generator from file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/201125_014532_flow_generator_train_None/checkpoint.pt
[2020-11-25 10:29:03,920][deepethogram.utils][INFO] - loading from checkpoint file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/201125_014532_flow_generator_train_None/checkpoint.pt...
[2020-11-25 10:29:05,789][deepethogram.dataloaders][INFO] - getting dataloaders: 2d convolution type detected
[2020-11-25 10:29:05,790][deepethogram.dataloaders][INFO] -  ~~~ augmentations ~~~
[2020-11-25 10:29:05,790][deepethogram.dataloaders][INFO] - {'test': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202])
),
 'train': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    RandomHorizontalFlip(p=0.5)
    RandomRotation(degrees=(-10, 10), resample=False, expand=False)
    ColorJitter(brightness=[0.75, 1.25], contrast=[0.9, 1.1], saturation=None, hue=None)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202])
),
 'val': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098, 0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202, 0.08265920461495736, 0.05720523456998572, 0.166993562276202])
)}
/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/dataloaders.py:1301: RuntimeWarning: divide by zero encountered in true_divide
  pos_weight = num_neg / num_pos
[2020-11-25 10:29:05,989][deepethogram.dataloaders][INFO] - Class counts: [ 300  475  715   98 1143   81  226  455    0    0    0    0    0]
[2020-11-25 10:29:05,989][deepethogram.dataloaders][INFO] - Pos weight: [10.64333333  6.35368421  3.88531469 34.64285714  2.055993   42.12345679
 14.45575221  6.67692308         inf         inf         inf         inf
         inf]
[2020-11-25 10:29:05,990][deepethogram.dataloaders][INFO] - Pos weight, weighted: [10.643333   6.3536844  3.8853147 34.642857   2.055993  42.123455
 14.455752   6.6769233  0.         0.         0.         0.
  0.       ]
[2020-11-25 10:29:05,990][deepethogram.dataloaders][INFO] - Softmax weight: [0.09037237 0.05707729 0.03791848 0.27665011 0.02371978 0.33471248
 0.11996332 0.05958618 0.         0.         0.         0.
 0.        ]
[2020-11-25 10:29:05,990][deepethogram.dataloaders][INFO] - Softmax weight transformed: [0.09037237 0.05707728 0.03791848 0.2766501  0.02371978 0.33471248
 0.11996332 0.05958618 0.         0.         0.         0.
 0.        ]
[2020-11-25 10:29:06,179][deepethogram.projects][INFO] - loading specified weights
[2020-11-25 10:29:06,328][deepethogram.feature_extractor.models.CNN][INFO] - Custom bias: Parameter containing:
tensor([-2.3649, -1.8490, -1.3572, -3.5451, -0.7208, -3.7406, -2.6711, -1.8987,
           -inf,    -inf,    -inf,    -inf,    -inf], requires_grad=True)
[2020-11-25 10:29:06,329][deepethogram.utils][INFO] - loading component spatial from file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/checkpoint.pt
[2020-11-25 10:29:06,329][deepethogram.utils][INFO] - loading from checkpoint file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/spatial/checkpoint.pt...
[2020-11-25 10:29:06,545][deepethogram.utils][WARNING] - 1.weight has different size: pretrained:torch.Size([700, 512]) model:torch.Size([13, 512])
[2020-11-25 10:29:06,545][deepethogram.utils][WARNING] - 1.bias has different size: pretrained:torch.Size([700]) model:torch.Size([13])
[2020-11-25 10:29:06,706][deepethogram.feature_extractor.models.CNN][INFO] - Custom bias: Parameter containing:
tensor([-2.3649, -1.8490, -1.3572, -3.5451, -0.7208, -3.7406, -2.6711, -1.8987,
           -inf,    -inf,    -inf,    -inf,    -inf], requires_grad=True)
[2020-11-25 10:29:06,706][deepethogram.utils][INFO] - loading component flow from file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/checkpoint.pt
[2020-11-25 10:29:06,706][deepethogram.utils][INFO] - loading from checkpoint file /projectnb2/dnn-motion/kubra/deepethogram/gui_logs/proj1-rec26_deepethogram/models/pretrained/200415_125824_hidden_two_stream_kinetics_degf/flow/checkpoint.pt...
[2020-11-25 10:29:06,958][deepethogram.utils][WARNING] - 1.weight has different size: pretrained:torch.Size([700, 512]) model:torch.Size([13, 512])
[2020-11-25 10:29:06,958][deepethogram.utils][WARNING] - 1.bias has different size: pretrained:torch.Size([700]) model:torch.Size([13])
[2020-11-25 10:29:06,993][__main__][INFO] - key metric: loss
[2020-11-25 10:29:07,026][deepethogram.dataloaders][INFO] - getting dataloaders: 2d convolution type detected
[2020-11-25 10:29:07,026][deepethogram.dataloaders][INFO] -  ~~~ augmentations ~~~
[2020-11-25 10:29:07,026][deepethogram.dataloaders][INFO] - {'test': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202])
),
 'train': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    RandomHorizontalFlip(p=0.5)
    RandomRotation(degrees=(-10, 10), resample=False, expand=False)
    ColorJitter(brightness=[0.75, 1.25], contrast=[0.9, 1.1], saturation=None, hue=None)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202])
),
 'val': Compose(
    Resize(size=[224, 224], interpolation=bilinear)
    ToTensor()
    Normalize(mean=[0.17030547916444036, 0.011406822383848917, 0.6321989001349098], std=[0.08265920461495736, 0.05720523456998572, 0.166993562276202])
)}
[2020-11-25 10:29:07,145][deepethogram.dataloaders][INFO] - Class counts: [ 300  475  715   98 1143   81  226  455    0    0    0    0    0]
[2020-11-25 10:29:07,145][deepethogram.dataloaders][INFO] - Pos weight: [10.64333333  6.35368421  3.88531469 34.64285714  2.055993   42.12345679
 14.45575221  6.67692308         inf         inf         inf         inf
         inf]
[2020-11-25 10:29:07,145][deepethogram.dataloaders][INFO] - Pos weight, weighted: [10.643333   6.3536844  3.8853147 34.642857   2.055993  42.123455
 14.455752   6.6769233  0.         0.         0.         0.
  0.       ]
[2020-11-25 10:29:07,145][deepethogram.dataloaders][INFO] - Softmax weight: [0.09037237 0.05707729 0.03791848 0.27665011 0.02371978 0.33471248
 0.11996332 0.05958618 0.         0.         0.         0.
 0.        ]
[2020-11-25 10:29:07,146][deepethogram.dataloaders][INFO] - Softmax weight transformed: [0.09037237 0.05707728 0.03791848 0.2766501  0.02371978 0.33471248
 0.11996332 0.05958618 0.         0.         0.         0.
 0.        ]
[2020-11-25 10:29:07,146][__main__][INFO] - Num training batches 111, num val: 363
[2020-11-25 10:29:07,149][deepethogram.stoppers][INFO] - Using stopper type learning_rate
[2020-11-25 10:29:07,149][__main__][INFO] - key metric: loss
  0%|                                                  | 0/1000 [00:00<?, ?it/s]
train loss: nan:   1%|\ufffd\ufffd\ufffd                         | 1/111 [00:03<05:32,  3.03s/itrain loss: nan:   1%|\ufffd\ufffd\ufffd                         | 1/111 [00:03<05:32,  3.03s/itrain loss: nan:   1%|\ufffd\ufffd\ufffd                         | 1/111 [00:05<05:32,  3.03s/itrain loss: nan:   3%|\ufffd\ufffd\ufffd                         | 3/111 [00:05<04:21,  2.42s/itrain loss: nan:   3%|\ufffd\ufffd\ufffd                         | 3/111 [00:05<04:21,  2.42s/itrain loss: nan:   3%|\ufffd\ufffd\ufffd                         | 3/111 [00:07<04:21,  2.42s/itrain loss: nan:   5%|\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd                        | 5/111 [00:07<03:37,  2.05strain loss: nan:   5%|\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd                        | 5/111 [00:07<03:37,  2.05strain loss: nan:   5%|\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd                        | 5/111 [00:09<03:37,  2.05s  0%|                                                  | 0/1000 [00:09<?, ?it/s]Traceback (most recent call last):                                              
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/feature_extractor/train.py", line 675, in <module>
    main()
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/feature_extractor/train.py", line 56, in main
    model = train_from_cfg(cfg)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/feature_extractor/train.py", line 216, in train_from_cfg
    dali=dali)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/feature_extractor/train.py", line 437, in train
    steps_per_epoch['train'], train_mode=True, device=device, dali=dali)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/feature_extractor/train.py", line 536, in loop_one_epoch
    batch = next(dataiter)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/dataloaders.py", line 614, in __getitem__
    label = self.labels[index]
IndexError: index 3526 is out of bounds for axis 0 with size 3493

[2020-11-25 10:29:17,955][deepethogram.gui.main][INFO] - Training finished.
[2020-11-25 10:29:17,956][deepethogram.gui.main][INFO] - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2020-11-25 10:29:17,991][deepethogram.gui.main][INFO] - Number finalized labels: 3
[2020-11-25 10:29:54,675][deepethogram.gui.main][INFO] - User has been idle for 60.0 seconds...
^[cc^C^X^Z
[1]+  Stopped                 deepethogram
(deg) [eryilmaz@scc-q28 deepethogram]$ 

```

<img width="1246" alt="Screen Shot 2020-11-25 at 2 12 08 PM" src="https://user-images.githubusercontent.com/34382537/100271950-51a69100-2f28-11eb-894c-83e3378ea059.png">

**Comment by jbohnslav** [comment]
Hmm, that is weird. Do you have fewer labels than you have video frames?

**Comment by KubraE** [comment]
Actually no, I think I have enough data. 
<img width="804" alt="Screen Shot 2020-11-25 at 9 41 39 PM" src="https://user-images.githubusercontent.com/34382537/100301872-1bd4cd00-2f67-11eb-9b91-4d1a66a04ce0.png">
However the number of finalized labels are also seems not correct, it should be more than 3.

**Comment by KubraE** [comment]
Created another project and started from scratch, problem solved. Thanks!

**Comment by jbohnslav** [comment]
Hi Kubra, do you have any idea what starting from scratch actually fixed? Did you actually relabel the files or just move the label files over? The solution to a bug should never be "relabel all the videos", because human labeling time is the most valuable resource.

**Comment by KubraE** [comment]
Hi Jim, I didn't repeat the labeling process. I am not sure what fixed the problem but I created another project, copied and pasted my label files after importing videos.
