### ISSUE TITLE
Problem with creating a new project in Linux --   File "/home/mona/anaconda3/lib/python3.7/site-packages/deepethogram/projects.py", line 46, in initialize_project     assert os.path.isdir(directory), 'Directory does not exist: {}'.format(directory) AssertionError: Directory does not exist: 

### ISSUE THREAD

**Issue by monajalal** [jbohnslav/deepethogram#3]
When I am trying to create a new project, it gives me path problem and the error on the path is similar to a Windows-based path

```
[2020-09-26 22:13:03,850][deepethogram.gui.main][INFO] - Configuration used: cmap: deepethogram
control_arrow_jump: 31
label_view_width: 31
notes: null
postprocessor:
  min_bout_length: 2
  type: min_bout
prediction_opacity: 0.2
run:
  type: gui
unlabeled_alpha: 0.1
vertical_arrow_jump: 3

Traceback (most recent call last):
  File "/home/mona/anaconda3/lib/python3.7/site-packages/deepethogram/gui/main.py", line 640, in _new_project
    labeler)
  File "/home/mona/anaconda3/lib/python3.7/site-packages/deepethogram/projects.py", line 46, in initialize_project
    assert os.path.isdir(directory), 'Directory does not exist: {}'.format(directory)
AssertionError: Directory does not exist: \home\mona\research\deepethogram

```

![Screenshot from 2020-09-26 22-13-58](https://user-images.githubusercontent.com/1892917/94354102-bc7d3e00-0045-11eb-97c1-c2bbf3258db0.png)

Please note this is rising from line 50 in 

https://github.com/jbohnslav/deepethogram/blob/master/deepethogram/gui/menus_and_popups.py
`        project_directory = project_directory.replace('/', '\\')`

**Comment by jbohnslav** [comment]
closed with 9407467 .
