### ISSUE TITLE
AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by toujames** [jbohnslav/deepethogram#33]
Hi Jim

I have a couple of questions:
I'm having some issues trying to train the sequence model through the GUI.
I have succesfully trained the flow generator and the feature extractor succesffully.
However, when I train the sequence model I get an AssertionError.

The other question I had was that is the sequence portion necessary?
I''m able use the 'infer' button near the feature extractor and the model is able to predict the behaviors.

Here's the full standard output when I click train sequence :
```
[2021-01-15 12:32:01,378][__main__][INFO] - Configuration used: 
[2021-01-15 12:32:01,385][__main__][INFO] - augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  normalization:
    N: 2441084928
    mean:
    - 0.5027036828932421
    - 0.48513365068507
    - 0.4612504518190313
    std:
    - 0.2723013599876207
    - 0.2523336957666119
    - 0.23650593991303887
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
compute:
  batch_size: 32
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  num_workers: 8
feature_extractor:
  arch: resnet18
  curriculum: true
  dropout_p: 0.9
  final_activation: sigmoid
  fusion: average
  inputs: both
  n_flows: 10
  n_rgb: 1
  sampler: null
  sampling_ratio: null
  weight_decay: 0
  weights: null
notes: null
preset: null
project:
  class_names:
  - background
  - PL
  - PC
  - PZ
  - PN
  - HL
  - HC
  - HN
  - HZ
  - H999
  - TL
  - TC
  - TN
  - TZ
  - T999
  config_file: /home/james/Documents/deepethogram_test2/project_config.yaml
  data_path: /home/james/Documents/deepethogram_test2/DATA
  labeler: j_m_k
  model_path: /home/james/Documents/deepethogram_test2/models
  name: deepethogram_test2
  path: /home/james/Documents/deepethogram_test2
reload:
  latest: false
  overwrite_cfg: false
  weights: null
run:
  model: sequence
  type: train
sequence:
  arch: tgmj
  bidirectional: false
  c_in: 1
  c_out: 8
  dropout_p: 0.5
  filter_length: 15
  hidden_dropout: 0.0
  hidden_size: 64
  input_dropout: 0.4
  latent_name: resnet18
  n_filters: 8
  nonlinear_classification: false
  nonoverlapping: false
  num_features: 64
  num_layers: 1
  output_name: null
  rnn_style: lstm
  sequence_length: 180
  soft_attn: false
  tgm_reduction: max
  weights: null
split:
  file: null
  reload: true
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
train:
  early_stopping_begins: 0
  loss_weight_exp: 1.0
  lr: 0.0001
  milestones:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  min_lr: 5.0e-07
  num_epochs: 1000
  patience: 5
  reduction_factor: 0.1
  scheduler: plateau
  steps_per_epoch:
    test: 20
    train: 1000
    val: 1000
  stopping_type: learning_rate
  viz: true
  weight_loss: true

[2021-01-15 12:32:01,387][__main__][INFO] - Training sequence model...
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Janna_BJ461_wall_B1
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Janna_STGT015_B3_wall
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Janna_XX318_B4_front
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Krish_BJ461_wall_B1
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Krish_STGT015_B3_wall
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Krish_XX318_B4_front
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Max_BJ461_wall_B1
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Max_STGT015_B3_wall
  warnings.warn('No {} file found in record: {}'.format(t, k))
/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/projects.py:637: UserWarning: No output file found in record: Max_XX318_B4_front
  warnings.warn('No {} file found in record: {}'.format(t, k))
[2021-01-15 12:32:01,407][deepethogram.dataloaders][INFO] - file Janna_XX238_wall_B4 assigned to split train
[2021-01-15 12:32:01,408][deepethogram.dataloaders][INFO] - ~~~~~ train val test split ~~~~~
{'test': {},
 'train': {'Janna_XX238_wall_B4': {'flow': None,
                                   'key': 'Janna_XX238_wall_B4',
                                   'label': '/home/james/Documents/deepethogram_test2/DATA/Janna_XX238_wall_B4/Janna_XX238_wall_B4_labels.csv',
                                   'output': '/home/james/Documents/deepethogram_test2/DATA/Janna_XX238_wall_B4/Janna_XX238_wall_B4_outputs.h5',
                                   'rgb': '/home/james/Documents/deepethogram_test2/DATA/Janna_XX238_wall_B4/Janna_XX238_wall_B4.mp4'}},
 'val': {}}
Traceback (most recent call last):
  File "/home/james/anaconda3/envs/deg/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/sequence/train.py", line 156, in <module>
    main()
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/sequence/train.py", line 42, in main
    model = train_from_cfg(cfg)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/sequence/train.py", line 52, in train_from_cfg
    dataloaders = get_dataloaders_from_cfg(cfg, model_type='sequence')
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/dataloaders.py", line 2688, in get_dataloaders_from_cfg
    valid_splits_only=True, return_logits=False)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/dataloaders.py", line 1441, in get_dataloaders_sequence
    store_in_ram=store_in_ram, return_logits=return_logits)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1.post1-py3.7.egg/deepethogram/dataloaders.py", line 913, in __init__
    self.dataset = data.ConcatDataset(datasets)
  File "/home/james/anaconda3/envs/deg/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 199, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore

```

**Comment by jbohnslav** [comment]
Hi Tou, thanks for the good questions. To answer the first-- the sequence model is not strictly necessary, because the feature extractor is trained to predict behaviors-- that's what you're seeing. However, I found (Figure 5G) that the sequence model consistently improves the predictions, and will definitely smooth them out. 

The bug is that the software was only able to find one label: if you look at the train, validation, test split, there is only one entry: `Janna_XX238_wall_B4`. Another note: all the warnings show that you have ~9 videos without "output files", which are created when you run inference on the feature extractor. 

Can you try hitting "feature_extractor: infer", select all the videos, and let it run? Then you can train a sequence model (and then run inference with that as well)

**Comment by toujames** [comment]
Thanks.
That fixed it. I'm able to train the sequence model and run inference.

I'll close the issue.
