### ISSUE TITLE
your_project/models folder empty

### ISSUE THREAD

**Issue by 0tist** [jbohnslav/deepethogram#37]
Hi, 

I'm using ubuntu 20.04, i started a new project with deepehtogram, i've labeled a couple of frames just to check if it's working on my machine.  

but i keep on getting this error, as per the documentation i'm supposed to download a model but the link is not valid.
the model will go inside the _your_project/models_ folder
currently the aforementioned folder contains nothing
`
Traceback (most recent call last):
  File "/home/arnablab/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram/gui/main.py", line 315, in flow_train
    args = self.generate_flow_train_args()
  File "/home/arnablab/anaconda3/envs/deg/lib/python3.7/site-packages/deepethogram/gui/main.py", line 302, in generate_flow_train_args
    weights = self.get_selected_models()['flow_generator']
TypeError: 'NoneType' object is not subscriptable
[2021-01-29 11:50:00,916][deepethogram.gui.main][INFO] - User has been idle for 60.0 seconds...
`

**Comment by jbohnslav** [comment]
Thanks for pointing this out. This should be fixed with 025950b. Please use the updated link to download the .zip file.
