### ISSUE TITLE
Feature Extractor Error

### ISSUE THREAD

**Issue by bwee** [jbohnslav/deepethogram#7]
Hi!  I've run through the Getting Started guide and have completed the FlowGenerator step and the manual labelling step.  However, when I go to train the FeatureExtractor, I get the following error in the terminal:

> Traceback (most recent call last):
  File "C:\Users\lab\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lab\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\feature_extractor\train.py", line 675, in <module>
    main()
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\hydra\main.py", line 24, in decorated_main
    strict=strict,
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\hydra\_internal\utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\hydra\_internal\hydra.py", line 86, in run
    job_subdir_key=None,
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\feature_extractor\train.py", line 56, in main
    model = train_from_cfg(cfg)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\feature_extractor\train.py", line 158, in train_from_cfg
    input_images=cfg.feature_extractor.n_flows + 1)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\dataloaders.py", line 2674, in get_dataloaders_from_cfg
    supervised=supervised, reduce=reduce, conv_mode=mode)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\dataloaders.py", line 2518, in get_video_dataloaders
    train_val_test)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\dataloaders.py", line 2159, in get_split_from_records
    split_dictionary = split_func(records, train_val_test)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\dataloaders.py", line 2067, in get_valid_split
    split_dict = train_val_test_split(records, train_val_test)
  File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram-0.0.1-py3.7.egg\deepethogram\dataloaders.py", line 2009, in train_val_test_split
    assert len(records) > 1
AssertionError
[2020-09-29 15:27:35,915][deepethogram.gui.main][INFO] - Training finished.
[2020-09-29 15:27:35,915][deepethogram.gui.main][INFO] - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2020-09-29 15:27:35,931][deepethogram.gui.main][INFO] - Number finalized labels: 1

I think the problem (whatever it is) is that "records" is currently 1 or 0.  Do you have any advice?

Thanks so much.

**Comment by jbohnslav** [comment]
Thanks for using the software! Here's a way to diagnose: can you open up your command line, activate your environment (probably `conda activate deg`), type `python`, then enter the following lines, except replace DATADIR with the full path to your project's DATA directory, e.g. `C:\DATA\flies_DEG_project\DATA`

```python
from deepethogram import projects
projects.get_records_from_datadir(DATADIR)
```

It should print out all the records it finds. I'm guessing that the problem has to do with "missing" labels, but this is a first check.

**Comment by bwee** [comment]
`{'092920_vid1': {'flow': None, 'label': '/users/lab/documents/deepethogram/deepethogram/projects/testproject_deepethogram/data\\092920_vid1\\092920_vid1_labels.csv', 'output': None, 'rgb': '/users/lab/documents/deepethogram/deepethogram/projects/testproject_deepethogram/data\\092920_vid1\\092920_vid1.avi', 'key': '092920_vid1'}}`

**Comment by jbohnslav** [comment]
Hmm, I see. Have you only labeled one video? In general, I think the code expects at least two videos, because one will be allocated to the training set and the other to the validation set.

**Comment by bwee** [comment]
Ah yeah that was it, thanks a ton
