### ISSUE TITLE
deg command line usage, omegaconf error

### ISSUE THREAD

**Issue by chgebhardt** [jbohnslav/deepethogram#83]
Hi,

Your package has the potential to make my life much easier combing through TB of behavior data. :) 

I installed DeepEthogram from source on our institutes GPU cluster (I dont have a decent GPU available to me otherwise). The command line pipeline seems to work (project initialization, adding videos, labels and pretrained models). I think i made sure I have the right filepath structure. I hit problems though when I start the training. First I wanted to train the flow_generator using the example command you give. 

I executed: 
python -m deepethogram.flow_generator.train project.config_file=/home/deepEtho_wrkdir/pup_retrieval_deepethogram/project_config.yaml flow_generator.arch=MotionNet compute.batch_size=16

I get this error then: 

Traceback (most recent call last):
  File "/home/.conda/envs/deg/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/.conda/envs/deg/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/ablab/users/downloads/deepethogram/deepethogram/flow_generator/train.py", line 16, in <module>
    from deepethogram.base import BaseLightningModule, get_trainer_from_cfg
  File "/share/ablab/users/downloads/deepethogram/deepethogram/base.py", line 11, in <module>
    import pytorch_lightning as pl
  File "/home/.conda/envs/deg/lib/python3.7/site-packages/pytorch_lightning-1.1.8-py3.7.egg/pytorch_lightning/__init__.py", line 68, in <module>
    from pytorch_lightning.core import LightningDataModule, LightningModule
  File "/home/.conda/envs/deg/lib/python3.7/site-packages/pytorch_lightning-1.1.8-py3.7.egg/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/home/.conda/envs/deg/lib/python3.7/site-packages/pytorch_lightning-1.1.8-py3.7.egg/pytorch_lightning/core/lightning.py", line 38, in <module>
    from pytorch_lightning.core.saving import ALLOWED_CONFIG_TYPES, ModelIO, PRIMITIVE_TYPES
  File "/home/.conda/envs/deg/lib/python3.7/site-packages/pytorch_lightning-1.1.8-py3.7.egg/pytorch_lightning/core/saving.py", line 42, in <module>
    from omegaconf.errors import UnsupportedValueType, ValidationError
ImportError: cannot import name 'UnsupportedValueType' from 'omegaconf.errors' (/home/.conda/envs/deg/lib/python3.7/site-packages/omegaconf/errors.py)

This seems to point at the omegaconf package (I have version 1.4.1) as the culprit? Or is that a pytorch probem at its core? The errors.py mentioned above does not contain an UnsupportedValueType class only MissingMandatoryValue, ValidationError, ReadonlyConfigError, UnsupportedInterpolationType. In any case, this should probably not run into instances where this is needed?  

Do you know what could cause that error?  Any help is appreciated.

Best,
chris

**Comment by chgebhardt** [comment]
I wish I could say that this was a targeted approach but updating omegaconf to version 2.0 seems to have done the trick (like suggested for the beta update). 

I can train the flow_generator now from the command line. I wonder if during the initial installation process files for the beta version of deg were installed but the environment.yml file didnt reflect that change?

**Comment by jbohnslav** [comment]
Glad you fixed it!
