### ISSUE TITLE
Feature extractor softmax configuration error

### ISSUE THREAD

**Issue by oliviayoo** [jbohnslav/deepethogram#97]
Hi!

I'm interested in improving the prediction results by updating the feature extractor and sequence inference models from `sigmoid` to `softmax`.

However, when I use `cfg.feature_extractor.final_activation = 'softmax'`, the config.yaml file updates appropriately, but I get an error and am unable to train the feature extractor. Without this command, and with the initial `sigmoid` final activation, my installation/code works just fine. 

I installed DeepEthogram a couple months ago - my intuition is that reinstalling/updating DeepEthogram might resolve this error. Do you think that would be correct? Otherwise, do you have any other ideas what could be going wrong? Thanks so much!

```
Traceback (most recent call last):
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 542, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py", line 85, in profile_iterable
    value = next(iterator)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 47, in _with_is_last
    for val in it:
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/deepethogram/data/datasets.py", line 406, in __getitem__
    return self.dataset[index]
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/deepethogram/data/datasets.py", line 366, in __getitem__
    label = np.where(label)[0][0].astype(np.int64)
IndexError: index 0 is out of bounds for axis 0 with size 0
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "featext_deg.py", line 68, in <module>
    feature_extractor = feature_extractor_train(cfg)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/deepethogram/feature_extractor/train.py", line 182, in feature_extractor_train
    trainer.fit(lightning_module)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 589, in train
    self.train_loop.on_train_end()
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 156, in on_train_end
    self.check_checkpoint_callback(should_update=True, is_last=True)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 190, in check_checkpoint_callback
    cb.on_validation_end(self.trainer, model)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 204, in on_validation_end
    self.save_checkpoint(trainer, pl_module)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 239, in save_checkpoint
    self._validate_monitor_key(trainer)
  File "/n/home03/oyoo/.conda/envs/newdeg/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 517, in _validate_monitor_key
    raise MisconfigurationException(m)
pytorch_lightning.utilities.exceptions.MisconfigurationException: ModelCheckpoint(monitor='val/f1_class_mean_nobg') not found in the returned metrics: ['train/loss']. HINT: Did you call self.log('val/f1_class_mean_nobg', tensor) in the LightningModule?
```

**Comment by oliviayoo** [comment]
I did have labels for this particular file, but reinstalling the software worked for me. Thanks!
